import { Inter } from 'next/font/google'
import '../global/globals.css'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '@/components/Footer'
import { AuthProvider } from '@/context/authContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pomodoro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
        <link rel="icon" href="../assets/chitkara-logo.ico" />
      </head>
      <body className={inter.className}>
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200'
        />
        <AuthProvider>
          <div className='sticky top-0 left-0 z-50 '>
            <Navbar />
            {/* <SpeedDial/> */}
          </div>
          <div>
            {children}
          </div>

          <div >
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
